# Julien


aliments = {
"Aliments":0,
"Cocktail de tomate et de palourdes":1,
"Jus de carottes":2,
"Jus de légumes, cocktail":3,
"Jus de légumes, cocktail, réduit en sodium":4,
"Jus de tomate":5,
"Jus de tomate, sans sel ajouté":6,
"Salade de chou, avec vinaigrette, maison":7,
"Salade de pommes de terre, maison":8,
"Sauce tomate pour spaghetti, en conserve":9,
"Sauce tomate, en conserve":10,
"Abricots crus":11,
"Abricots, séchés":12,
"Ananas, en conserve, dans du jus":13,
"Ananas, en dés":14,
"Avocat":15,
"Banane":16,
"Bleuets crus":17,
"Bleuets, congelés, non sucrés":18,
"Canneberges séchées, sucrées":19,
"Cerises de terre":20,
"Cerises sucrées":21,
"Clémentine":22,
"Cocktail aux fruits, en conserve, dans du jus":23,
"Cocktail aux fruits, en conserve, sirop léger":24,
"Dattes séchées":25,
"Figues crues":26,
"Figues séchées":27,
"Fraises":28,
"Fraises, congelées, non sucrées":29,
"Framboises":30,
"Grenade (9,5 cm diam)":31,
"Kiwi":32,
"Litchi":33,
"Mangue":34,
"Melon d'eau (pastèque), en dés":35,
"Melon, cantaloup, en dés":36,
"Melon, miel, en dés":37,
"Mûres":38,
"Nectarine":39,
"Orange":40,
"Pamplemousse blanc":41,
"Pamplemousse rose ou rouge":42,
"Papaye, en dés":43,
"Pêche":44,
"Pêches, en conserve, moitiés ou tranchées, dans du jus":45,
"Pêches, en conserve, moitiés ou tranchées, dans l'eau":46,
"Pêches, en conserve, moitiés ou tranchées, sirop léger":47,
"Plantain, cuit au four ou bouilli, tranché":48,
"Poire avec pelure":49,
"Poires, en conserve, moitiés, dans du jus":50,
"Poires, en conserve, moitiés, dans l'eau":51,
"Poires, en conserve, moitiés, sirop léger":52,
"Pomme avec pelure (7cm diam)":53,
"Prune":54,
"Pruneaux, séchés":55,
"Pruneaux, séchés, cuits sans sucre":56,
"Purée de pommes, non sucrée":57,
"Raisins":58,
"Raisins secs":59,
"Rhubarbe, congelée, cuite avec sucre":60,
"Salade de fruits tropicaux, en conserve, dans du jus":61,
"Salade de fruits tropicaux, en conserve, sirop épais":62,
"Tangerine (mandarine)":63,
"Tangerines (mandarines), en conserve, dans du jus, égouttées":64,
"Jus d'ananas, prêt-à-boire, avec vitamine C":65,
"Jus de canneberges, non sucré, prêt-à-boire":66,
"Jus de citron, en conserve ou en bouteille":67,
"Jus de grenade, prêt-à-boire":68,
"Jus de lime, en conserve ou en bouteille":69,
"Jus de pamplemousse, prêt-à-boire, non sucré ou fraîchement pressé":70,
"Jus de pamplemousse, prêt-à-boire, sucré":71,
"Jus de pomme, prêt-à-boire, avec vitamine C":72,
"Jus de pruneaux, prêt-à-boire":73,
"Jus de raisins, congelé, sucré, dilué, avec vitamine C":74,
"Jus de raisins, prêt-à-boire, avec vitamine C":75,
"Jus d'orange et pamplemousse, prêt-à-boire":76,
"Jus d'orange, congelé, dilué":77,
"Jus d'orange, fraises et banane, prêt-à-boire":78,
"Jus d'orange, prêt-à-boire":79,
"Jus d'orange, prêt-à-boire, réfrigéré, avec vitamine D et calcium":80,
"Jus, cocktail de canneberges et pomme, prêt-à-boire, peu de Calories, avec vitamine C":81,
"Jus, cocktail de canneberges, prêt-à-boire, avec vitamine C":82,
"Nectar, abricot":83,
"Nectar, mangue":84,
"Babeurre":85,
"Boisson de riz, nature et arômatisée, enrichie":86,
"Boisson de soya au chocolat, enrichie":87,
"Boisson de soya non sucrée, enrichie":88,
"Boisson de soya, originale et vanille, enrichie":89,
"Lait au chocolat, 1% M.G.":90,
"Lait au chocolat, 2% M.G.":91,
"Lait écrémé":92,
"Lait partiellement écrémé, 1% M.G.":93,
"Lait partiellement écrémé, 2% M.G.":94,
"Lait, partiellement écrémé, 2% M.G., avec solides de lait ajoutés":95,
"Lait entier, 3.3% M.G.":96,
"Lait concentré sucré, en conserve (Eagle BrandMC)":97,
"Lait évaporé, écrémé, en conserve, dilué, 0,2% M.G.":98,
"Lait évaporé, écrémé, en conserve, non dilué, 0,2% M.G.":99,
"Lait évaporé, entier, en conserve, dilué, 7,8% M.G.":100,
"Lait évaporé, entier, en conserve, non dilué, 7,8% M.G.":101,
"Lait évaporé, partiellement écrémé, en conserve, dilué, 2% M.G.":102,
"Lait évaporé, partiellement écrémé, en conserve, non dilué, 2% M.G.":103,
"Lait reconstitué à base de poudre de lait écrémé":104,
"Poudre de lait écrémé":105,
"Chocolat chaud, maison, cacao et lait 2%":106,
"Chocolat chaud, préparation commerciale et eau":107,
"Chocolat chaud, préparation commerciale et lait 2%":108,
"Chocolat chaud, préparation commerciale sucrée à l'aspartame et eau":109,
"Déjeuner instantané, préparation commerciale et lait 2%":110,
"Lait au chocolat, poudre arômatisée au chocolat et lait 2%":111,
"Lait au chocolat, sirop et lait 2%":112,
"Lait de poule":113,
"Lait frappé à la vanille":114,
"Lait frappé au chocolat":115,
"Fromage frais (Danimal MC, MinigoMC)":116,
"Kéfir, nature":117,
"Parfait au yogourt avec petits fruits et granola":118,
"Yogourt à boire":119,
"Yogourt, nature, 1-2% M.G.":120,
"Yogourt, nature, 2-4% M.G.":121,
"Yogourt, nature, sans gras":122,
"Yogourt, vanille ou fruits, 1-2% M.G.":123,
"Yogourt, vanille ou fruits, sans gras":124,
"Yogourt, vanille ou fruits, sans gras, sucré à l'édulcorant":125,
"Bleu":126,
"Brick":127,
"Brie":128,
"Camembert":129,
"Cheddar":130,
"Cheddar, peu de gras (18% M.G.)":131,
"Edam":132,
"Féta":133,
"Fromage à la crème, léger":134,
"Fromage à la crème, régulier":135,
"Fromage cottage (1% M.G.)":136,
"Fromage de chèvre à pâte molle":137,
"Fromage, imitation":138,
"Gouda":139,
"Gruyère":140,
"Mozzarella (22,5% M.G.)":141,
"Mozzarella partiellement écrémé (16,5% M.G.)":142,
"Parmesan, râpé":143,
"Préparation de fromage fondu à tartiner (Cheez WhizMC)":144,
"Préparation de fromage fondu à tartiner, léger (Cheez Whiz Légermc)":145,
"Préparation de fromage fondu, tranches minces":146,
"Préparation de fromage fondu, tranches minces, léger":147,
"Ricotta, partiellement écrémé":148,
"Romano, râpé":149,
"Suisse (Emmental)":150,
"Suisse fondu, tranches minces":151,
"Crème à fouetter, 35% M.G., non fouettée":152,
"Crème à fouetter, 35% M.G., sucrée, fouettée":153,
"Crème fouettée, en aérosol":154,
"Crème sure légère, 5% M.G.":155,
"Crème sure, 14% M.G.":156,
"De table, 18% M.G.":157,
"Moitié-moitié, 10% M.G.":158,
"Colorant à café, en poudre":159,
"Colorant à café, en poudre, léger":160,
"Colorant à café, liquide, congelé":161,
"Garniture à dessert congelée":162,
"Garniture à dessert congelée, peu de gras":163,
"Garniture à dessert en aérosol":164,
"Garniture à dessert en poudre, préparée avec lait 2%":165,
"Chocolat, prêt-à-manger":166,
"Chocolat, prêt-à-manger, sans gras":167,
"Riz, maison":168,
"Riz, prêt-à-manger":169,
"Tapioca, prêt-à-manger":170,
"Tapioca, prêt-à-manger, sans gras":171,
"Toutes saveurs, instantané, préparé avec lait 2%":172,
"Vanille, prêt-à-manger":173,
"Vanille, prêt-à-manger, sans gras":174,
"Blanc d'oeuf cuit":175,
"Jaune d'oeuf cuit":176,
"Oeuf cuit dur (à la coque)":177,
"Oeuf poché":178,
"Oeuf frit":179,
"Oeufs bénédictine":180,
"Oeufs brouillés, faits avec 2 oeufs":181,
"Omelette au fromage, faite avec 2 oeufs":182,
"Omelette espagnole (champignons, oignons, poivrons verts, tomates)":183,
"Omelette western (poivrons verts, jambon, oignons)":184,
"Succédané d'oeuf (jaunes remplacés), congelé, cuit":185,
"Aiglefin, au four ou grillé":186,
"Anchois, en conserve dans l'huile, égouttés":187,
"Bar (achigan), espèces diverses, au four ou grillé":188,
"Barbue de rivière à élevage, au four ou grillé":189,
"Cisco (hareng de lac), au four ou grillé":190,
"Cisco (hareng de lac), cru":191,
"Corégone de lac, autochtone, au four":192,
"Doré (jaune), au four ou grillé":193,
"Éperlan, pané et frit":194,
"Flétan de l'Atlantique ou Pacifique, au four ou grillé":195,
"Gefiltefish":196,
"Goberge de l'Atlantique, au four ou grillé":197,
"Grand brochet, au four ou grillé":198,
"Hareng de l'Atlantique, fumé et salé":199,
"Lotte (loche), crue":200,
"Maquereau bleu de l'Atlantique, au four ou grillé":201,
"Morue de l'Atlantique, au four ou grillé":202,
"Morue de l'Atlantique, déshydratée et salée, trempée dans l'eau":203,
"Omble chevalier, cuit":204,
"Ombre, au four ou grillé":205,
"Sardines de l'Atlantique, en conserve dans l'huile, égouttées avec arêtes":206,
"Sardines du Pacifique, en conserve dans de la sauce tomate, égouttées avec arêtes":207,
"Saumon coho d'élevage, au four ou grillé":208,
"Saumon de l'Atlantique d'élevage, au four ou grillé":209,
"Saumon fumé":210,
"Saumon fumé, lox":211,
"Saumon keta, au four ou grillé":212,
"Saumon keta, en conserve, égoutté, avec arêtes, sans sel":213,
"Saumon keta, en conserve, égoutté, avec arêtes, salé":214,
"Saumon rose, en conserve, égoutté, avec arêtes, salé":215,
"Saumon sockeye, au four ou grillé":216,
"Saumon, oeufs, crus":217,
"Saumon, royal ou quinnat, fumé, conserve":218,
"Sébaste de l'Atlantique, au four ou grillé":219,
"Sole (poisson plat), au four ou grillé":220,
"Thon, chair pâle, en conserve dans l'eau, égoutté, salé":221,
"Thon, chair pâle, en conserve dans l'huile, égoutté, salé":222,
"Truite arc-en-ciel d'élevage, au four ou grillée":223,
"Turbot, au four ou grillé":224,
"Vivaneau, espèces diverses, au four ou grillé":225,
"Crabe des neiges, bouilli ou cuit à la vapeur":226,
"Crabe, en conserve, égoutté":227,
"Crevettes, bouillies ou cuites à la vapeur":228,
"Écrevisse d'élevage, espèces diverses, bouillies ou cuites à la vapeur":229,
"Homard, bouilli ou cuit à la vapeur":230,
"Huîtres, bouillies ou cuites à la vapeur":231,
"Huîtres, crues":232,
"Huîtres, en conserve, chair et liquide":233,
"Moule, bouillies ou cuites à la vapeur":234,
"Palourdes, espèces diverses, bouillies ou cuites à la vapeur":235,
"Palourdes, espèces diverses, en conserve, égouttées":236,
"Pétoncles, cuits à la vapeur":237,
"Bâtonnets de poisson, congelés, réchauffés (10cm x 2,5cm x 1,3cm)":238,
"Beignet (galette) de crabe":239,
"Beignet (galette) de poisson":240,
"Calmars panés et frits":241,
"Caviar, noir ou rouge":242,
"Crevettes, panées et frites":243,
"Filet de poisson, dans une pâte à frire, frit":244,
"Salade de thon":245,
"Simili-crabe, à base de surimi":246,
"Aloyau, bœuf, maigre et gras, grillé":247,
"Boeuf à ragoût, maigre, mijoté":248,
"Boeuf haché, extra maigre, émietté, sauté":249,
"Boeuf haché, maigre, émietté, sauté":250,
"Boeuf haché, mi-maigre, émietté, sauté":251,
"Boeuf haché, régulier, émietté, sauté":252,
"Bout-de-côtes, maigre et gras, mijoté":253,
"Contre-filet, bifteck, maigre et gras, grillé":254,
"Côte, bifteck, maigre et gras, grillé":255,
"Côte, rôti, maigre et gras, rôti":256,
"Côtes croisées, rôti, maigre et gras, rôti":257,
"Coupes diverses, maigre et gras, cuites":258,
"Croupe, rôti, maigre et gras, rôti":259,
"Extérieur de ronde, bifteck, maigre et gras, braisé":260,
"Extérieur de ronde, rôti, maigre et gras, rôti":261,
"Faux filet, bifteck, maigre et gras, grillé":262,
"Flanc, bifteck, maigre et gras, braisé":263,
"Haut de surlonge, bifteck, maigre et gras, grillé":264,
"Intérieur de ronde, bifteck, maigre et gras, braisé":265,
"Intérieur de ronde, rôti, maigre et gras, rôti":266,
"Longe, filet, maigre et gras, rôti":267,
"Noix de ronde, bifteck, maigre et gras, braisé":268,
"Noix de ronde, rôti, maigre et gras, rôti":269,
"Palette, bifteck, maigre et gras, braisé":270,
"Palette, rôti, maigre et gras, braisé":271,
"Pointe de surlonge, rôti, maigre et gras, rôti":272,
"Cuisseau de veau, maigre et gras, pané, sauté":273,
"Cuisseau de veau, maigre et gras, rôti":274,
"Épaule, maigre et gras, rôtie":275,
"Escalope de veau de grain, sautée":276,
"Escalope de veau de lait, sautée":277,
"Longe, maigre et gras, rôtie":278,
"Veau à ragoût, maigre, braisé":279,
"Veau haché, grillé":280,
"Côtelette, longe, coupe du milieu, maigre et gras, grillée":281,
"Côtelette, longe, coupe du milieu, maigre et gras, sautée":282,
"Côtes levées de dos, maigre et gras, rôties":283,
"Côtes levées, maigre et gras, mijotées et rôties":284,
"Cuisse, croupe, maigre et gras, rôtie":285,
"Épaule, entière, maigre et gras, rôtie":286,
"Épaule, soc, maigre et gras, rôtie":287,
"Longe, bout de côtes, maigre et gras, grillée":288,
"Longe, bout de côtes, maigre et gras, sautée":289,
"Longe, filet, maigre, rôtie":290,
"Porc haché, maigre, sauté":291,
"Porc haché, mi-maigre, sauté":292,
"Américain, frais, côtes, maigre et gras, cuit":293,
"Américain, frais, épaule, entière, maigre et gras, cuit":294,
"Américain, frais, gigot, entier, maigre et gras, cuit":295,
"Américain, frais, haché, cuit":296,
"Américain, frais, jarret, maigre et gras, cuit":297,
"Américain, frais, longe, maigre et gras, cuit":298,
"Nouvelle-Zélande, congelé, côte, maigre et gras, rôti":299,
"Nouvelle-Zélande, congelé, coupes diverses, maigre et gras, cuit":300,
"Nouvelle-Zélande, congelé, épaule, entier, maigre et gras, braisé":301,
"Nouvelle-Zélande, congelé, gigot, entier, maigre et gras, rôti":302,
"Nouvelle-Zélande, congelé, jarret, maigre et gras, braisé":303,
"Nouvelle-Zélande, congelé, longe, maigre et gras, grillé":304,
"Bernache du Canada (outarde), viande, rôtie":305,
"Canard domestiqué, rôti":306,
"Canard sauvage, cuit":307,
"Dinde hachée, cuite":308,
"Dinde, viande blanche et peau, rôtie":309,
"Dinde, viande blanche, rôtie":310,
"Dinde, viande brune et peau, rôtie":311,
"Dinde, viande brune, rôtie":312,
"Lagopède, viande, cuite":313,
"Oie domestiquée, viande, rôtie":314,
"Poulet à griller, aile, viande et peau, rôtie":315,
"Poulet à griller, haut de cuisse, viande et peau, rôti":316,
"Poulet à griller, haut de cuisse, viande, rôti":317,
"Poulet à griller, pilon, viande et peau, rôti":318,
"Poulet à griller, pilon, viande, rôti":319,
"Poulet à griller, poitrine, viande et peau, rôtie":320,
"Poulet à griller, poitrine, viande, rôtie":321,
"Poulet à griller, viande et peau, rôties":322,
"Poulet à griller, viande, rôtie":323,
"Poulet de Cornouailles, viande et peau, rôties":324,
"Poulet haché, maigre, cuit":325,
"Tétras du Canada, viande, cuite":326,
"Autruche, intérieur de cuisse, cuite":327,
"Bison, rôti":328,
"Caribou (renne), rôti":329,
"Castor, rôti":330,
"Cheval, rôti":331,
"Chèvre, rôtie":332,
"Chevreuil, rôti":333,
"Émeu, intérieur de pilon, grillé":334,
"Lapin, coupes diverses, rôti":335,
"Narval, peau (muktuk), crue":336,
"Orignal, rôti":337,
"Ours, mijoté":338,
"Phoque, viande, bouillie":339,
"Coeur de boeuf, mijoté":340,
"Foie de boeuf, sauté":341,
"Foie de poulet, sauté":342,
"Foie de veau, sauté":343,
"Langue de boeuf, en conserve ou marinée":344,
"Ris de veau (thymus), braisé":345,
"Rognon de boeuf, mijoté":346,
"Bacon de dos, porc, grillé":347,
"Bacon, porc, grillé, sauté ou rôti":348,
"Bacon, porc, grillé, sauté ou rôti, réduit en sodium":349,
"Boeuf salé, pointe de poitrine, cuit":350,
"Bologne, boeuf et porc":351,
"Bologne, boeuf et porc, léger":352,
"Bologne, poulet":353,
"Cretons":354,
"Dinde en flocons, en conserve":355,
"Jambon en flocons, en conserve":356,
"Jambon, extra-maigre, en conserve":357,
"Jambon, maigre, en conserve":358,
"Jambon, maigre, rôti":359,
"Jambon, maigre et régulier, rôti":360,
"Pastrami au boeuf":361,
"Pâté de foie, en conserve":362,
"Pepperoni, porc et boeuf":363,
"Porc, salé, épaule, soc roulé (toupie), maigre et gras, rôti":364,
"Poulet en flocons, en conserve":365,
"Salami, boeuf et porc":366,
"Salami, boeuf et porc, sec":367,
"Salami, porc et boeuf, moins de sel":368,
"Saucisse à la dinde, cuite":369,
"Saucisse à déjeuner au porc et boeuf, cuite":370,
"Saucisse à déjeuner au porc, cuite":371,
"Saucisse Bratwurst au porc, cuite":372,
"Saucisse fumée au boeuf":373,
"Saucisse fumée au boeuf et porc":374,
"Saucisse fumée au boeuf et porc, légère":375,
"Saucisse fumée au poulet":376,
"Saucisse italienne au porc, cuite":377,
"Saucisse viennoise (cocktail), boeuf et porc, en conserve":378,
"Saucisson de foie de porc":379,
"Saucisson d'été au boeuf":380,
"Saucisson Kielbasa (Kolbassa), porc et boeuf":381,
"Viande froide, boeuf, tranché mince":382,
"Viande froide, jambon extra-maigre (5% gras)":383,
"Viande froide, jambon régulier (11% gras)":384,
"Viande froide, poitrine de dinde":385,
"Viande froide, poitrine de poulet":386,
"Viande froide, poitrine de poulet, peu de gras":387,
"Viande froide, simili poulet":388,
"Croquettes panées (genre poulet) sans viande":389,
"Galette de soya":390,
"Galette végétarienne":391,
"Sans-viande hachée":392,
"Saucisse fumée végétarienne":393,
"Tofu, régulier, ferme et extra ferme":394,
"Tofu, soyeux, mou":395,
"Viande froide végétarienne":396,
"Falafel, maison":397,
"Fèves au lard avec porc, en conserve":398,
"Fèves au lard nature ou végétariennes, en conserve":399,
"Fèves au lard, maison":400,
"Haricots à oeil noir, en conserve, non drainé":401,
"Haricots blancs, en conserve, non drainé":402,
"Haricots blancs, petits, en conserve, non drainé":403,
"Haricots de soya, bouillis":404,
"Haricots frits, en conserve":405,
"Haricots noirs, en conserve, non drainé":406,
"Haricots pinto, en conserve, non drainé":407,
"Haricots rouge foncé, en conserve, non drainé":408,
"Hoummos (hummus), commercial":409,
"Lentilles, bouillies, salées":410,
"Lentilles, roses, bouillies":411,
"Pois cassés, bouillis":412,
"Pois chiches (garbanzo), en conserve, non drainé":413,
"Arachides, toutes variétés, écalées, rôties":414,
"Arachides, toutes variétés, écalées, rôties à l'huile, salées":415,
"Beurre d'arachide crémeux, léger":416,
"Beurre d'arachide crémeux, matières grasses, sucre et sel ajoutés":417,
"Beurre d'arachide croquant, matières grasses, sucre et sel ajoutés":418,
"Beurre d'arachide naturel":419,
"Amandes séchées":420,
"Amandes, rôties dans l'huile":421,
"Amandes, rôties, salées":422,
"Grenoble, séchées":423,
"Macadamia, rôties, salées":424,
"Noisettes ou avelines, séchées":425,
"Noix d'acajou, rôties, salées":426,
"Noix de Brésil, séchées":427,
"Noix mélangées, rôties":428,
"Noix mélangées, rôties dans l'huile, salées":429,
"Noix mélangées, rôties, salées":430,
"Pacanes, séchées":431,
"Pignons, séchés":432,
"Pistaches, écalées, rôties, salées":433,
"Beurre d'acajou":434,
"Beurre d'amande":435,
"Beurre de sésame, tahini":436,
"Graines de citrouille et de courge, écalées, séchées":437,
"Graines de lin, entières et moulues":438,
"Graines de tournesol, rôties, salées, écalées":439,
"Pain à l'ail":440,
"Pommes de terre, frites":441,
"Rondelles d'oignon, panées et frites":442,
"Courgettes, panées et frites, bâtonnets":443,
"Donair / Gyro":444,
"Hamburger au fromage, galette double, avec condiments et légumes":445,
"Hamburger au fromage, une galette, nature":446,
"Hamburger végétarien, une galette, avec condiments et légumes":447,
"Hamburger, galette double, avec condiments":448,
"Hamburger, une galette, nature":449,
"Sandwich au poisson pané":450,
"Sandwich au poulet grillé, avec condiments et légumes":451,
"Sandwich au poulet pané, avec condiments et légumes":452,
"Sandwich déjeuner, bagel avec jambon, œuf et fromage":453,
"Sandwich déjeuner, biscuit poudre à pâte avec œuf, fromage et bacon":454,
"Sandwich déjeuner, muffin anglais avec œuf, fromage et bacon":455,
"Sandwich roulé au poulet ranch":456,
"Sandwich sous-marin (6 pouces), avec poulet grillé/rôti":457,
"Sandwich sous-marin (6 pouces), avec thon":458,
"Sandwich sous-marin (6 pouces), avec viandes froides":459,
"Sandwich sous-marin (6 pouces), végétarien":460,
"Boulettes de poulet à la sauce aigre-douce":461,
"Chow mein au poulet":462,
"Guy ding au poulet et aux amandes":463,
"Poulet Général Tao/Tso":464,
"Riz frit au poulet":465,
"Rouleau impérial (egg roll)":466,
"Sauté de boeuf et brocoli":467,
"Soupe aigre-piquante":468,
"Soupe won ton":469,
"Pizza avec fromage (moyenne - 12 pouces)":470,
"Pizza avec fromage et légumes (moyenne - 12 pouces)":471,
"Pizza avec fromage et pepperoni (moyenne - 12 pouces)":472,
"Pizza avec fromage, viande et légumes (moyenne - 12 pouces)":473,
"Chili con carne":474,
"Hot dog, nature":475,
"Poulet frit (morceaux)":476,
"Poulet, pané et frit, désossé (pépites)":477,
"Saucisse fumée enrobée de farine de maïs (PogoMC)":478,
"Burrito avec boeuf, fromage et piments forts":479,
"Burrito avec haricots et fromage":480,
"Fajita au poulet":481,
"Nachos avec fromage":482,
"Quesadilla avec viande":483,
"Salade de taco":484,
"Taco avec boeuf, fromage, salsa et légumes":485,
"Jambon":486,
"Oeufs durs":487,
"Rôti de bœuf, nature":488,
"Salade de saumon":489,
"Sandwich chaud au poulet":490,
"Sandwich club":491,
"César":492,
"César avec poulet":493,
"Grecque":494,
"Jardinière":495,
"Salade de pâtes avec légumes":496,
"Lasagne avec sauce à la viande (7,5cm x 9cm)":497,
"Lasagne, végétarienne (7,5cm x 9cm)":498,
"Macaroni à la viande avec soupe aux tomates":499,
"Macaroni au fromage (Dîner KraftMC)":500,
"Spaghetti avec sauce à la viande":501,
"Spaghetti avec sauce crémeuse":502,
"Boulettes de viande à la sauce aigre-douce":503,
"Pad Thaï":504,
"Pâté au boeuf, commercial, individuel":505,
"Pâté au poulet, commercial, individuel":506,
"Pâté chinois":507,
"Poulet au beurre":508,
"Poutine":509,
"Ragoût de bœuf":510,
"Samosa, végétarien":511,
"Sauté au boeuf":512,
"Sauté au poulet":513,
"Sauté au tofu":514,
"Sushi avec légumes, sans poisson":515,
"Sushi avec poisson":516,
"Tourtière maison (20cm diam)":517,
"Aux légumes, chunky":518,
"Boeuf ou poulet, bouillon/consommé":519,
"Boeuf, chunky":520,
"Chaudrée de palourdes, Manhattan":521,
"Minestrone, chunky":522,
"Pois cassés et jambon, chunky":523,
"Poulet et légumes, chunky":524,
"Poulet et nouilles, chunky":525,
"Poulet et nouilles, peu de gras, moins de sel":526,
"Boeuf et nouilles":527,
"Bouillon de poulet":528,
"Crème de champignons":529,
"Légumes et boeuf":530,
"Tomates":531,
"Tomates, moins de sel":532,
"Végétarienne aux légumes":533,
"Chaudrée de palourdes, Nouvelle-Angleterre":534,
"Crème de champignons, moins de sel":535,
"Crème de poulet":536,
"Crème de tomates":537,
"Minestrone":538,
"Nouilles Ramen, saveur de poulet, cuites":539,
"Oignon":540,
"Tomates et légumes":541,
"Crème de légumes":542,
"Légumes":543,
"Lentilles":544,
"Oignon, gratinée":545,
"Pois cassés avec jambon":546,
"Poulet et nouilles":547,
"Beurre":548,
"Margarine, dure, ImperialMc, huiles de soya et canola (hydrogénée)":549,
"Margarine, molle, Becel Mc, huiles de canola et carthame (non-hydrogenée)":550,
"Margarine, molle, Becel Mc, légère, huiles de canola et carthame (non-hydrogenée)":551,
"Margarine, molle, ChefmasterMc, huiles végétales non spécifiées (hydrogénée)":552,
"Margarine, molle, composite":553,
"Margarine, molle, ImperialMc, huile de soya (non-hydrogénée)":554,
"Margarine, molle, Lactantia Mc, huile de soya (hydrogénée)":555,
"Tartinade (20% beurre / 80% margarine)":556,
"Tartinade (50% beurre / 50% margarine)":557,
"Arachide":558,
"Canola":559,
"Graines de lin":560,
"Maïs":561,
"Olive":562,
"Pépins de raisins":563,
"Sésame":564,
"Soya":565,
"Tournesol":566,
"Gras de bacon":567,
"Saindoux":568,
"Shortening":569,
"César, crémeuse":570,
"César, crémeuse, peu de Calories":571,
"Française":572,
"Française, peu de gras":573,
"Fromage bleu":574,
"Fromage bleu, peu de Calories":575,
"Huile et vinaigre":576,
"Italienne":577,
"Italienne, peu de Calories":578,
"Mayonnaise":579,
"Mayonnaise, légère":580,
"Mille Îles":581,
"Mille Îles, peu de Calories":582,
"Ranch":583,
"Ranch, peu de gras":584,
"Sauce à salade, type mayonnaise":585,
"Sauce à salade, type mayonnaise, légère":586,
"Sauce à salade, type mayonnaise, sans gras":587,
"Vinaigrette crémeuse, sans gras":588,
"Vinaigrette non crémeuse, sans gras":589,
"À glacer (en poudre)":590,
"Blanc":591,
"Cassonade":592,
"Miel":593,
"Substitut de sucre, aspartame (EqualMc)":594,
"Substitut de sucre, sucralose (Splendamc)":595,
"Mélasse":596,
"Sirop de chocolat, consistance claire":597,
"Sirop de maïs":598,
"Sirop de table":599,
"Sirop d'érable":600,
"Confiture":601,
"Gelée":602,
"Marmalade":603,
"Tartinade de type confiture - double fruit":604,
"Tartinade de type confiture - double fruit - teneur réduite en sucre":605,
"Garniture au chocolat, consistance épaisse":606,
"Garniture aux fraises":607,
"Garniture ou tartinade, caramel écossais":608,
"Garniture pour tarte aux cerises, en conserve":609,
"Tartinade au chocolat et noisettes (NutellaMC)":610,
"Bonbon dur":611,
"Bonbon dur, moins de sucre":612,
"Bonbon enrobé de chocolat, sucré avec sorbitol":613,
"Bonbons haricots (jellybeans)":614,
"Caramel":615,
"Caramel au beurre":616,
"Caramel écossais":617,
"Croquants au sésame":618,
"Fudge, chocolat, maison":619,
"Gomme à mâcher":620,
"Gomme à mâcher sans sucre":621,
"Guimauves":622,
"Jujubes":623,
"Réglisse aux fraises (TwizzlersMC)":624,
"Roulé aux fruits":625,
"Skittles Mc":626,
"Sucre à la crème, maison":627,
"Amandes enrobées de chocolat":628,
"Arachides enrobées de chocolat":629,
"Biscuits enrobés de caramel recouvert de chocolat (TwixMc)":630,
"Caramel au beurre croquant, enrobé de chocolat (SkorMC)":631,
"Caramel avec noix, enrobé de chocolat (TurtlesMC)":632,
"Caramel enrobé de chocolat (RoloMC, CaramilkMC)":633,
"Chocolat au lait en tablette ou en brisures":634,
"Chocolat au lait et riz croquant (Nestlé CrunchMC)":635,
"Chocolat enrobé de bonbons (M&M'SMC, SmartiesMC)":636,
"Chocolat malt-nougat et caramel, enrobé de chocolat (MarsMC)":637,
"Chocolat, mi-sucré, en tablette ou en brisures":638,
"Fondant enrobé de chocolat (After EightMC)":639,
"Fudge, caramel et noix, enrobé de chocolat (Oh Henry!MC)":640,
"Gaufrette enrobée de chocolat (Kit KatMc, Coffee CrispMC)":641,
"Moules au beurre d'arachide (Reese's MC)":642,
"Noix de coco enrobée de chocolat (Bounty Mc, Almond JoyMC)":643,
"Raisins secs enrobés de chocolat (GlosetteMC)":644,
"Barre de fruits et jus":645,
"Barre de lait glacé au chocolat (FudgesicleMC)":646,
"Cornet de crème glacée, vanille, enrobé de chocolat, avec noix":647,
"Cornet de crème glacée, vanille, molle":648,
"Crème glacée molle avec biscuits OreoMc (Blizzard MC, McFlurryMc)":649,
"Crème glacée, chocolat":650,
"Crème glacée, fraises":651,
"Crème glacée, sandwich":652,
"Crème glacée, sans produits laitiers":653,
"Crème glacée, vanille, peu de gras":654,
"Crème glacée, vanille, peu de gras, sucrée à l'aspartame":655,
"Crème glacée, vanille, premium":656,
"Crème glacée, vanille, régulière":657,
"Sorbet à l'orange":658,
"Sucette glacée (popsicle)":659,
"Yogourt glacé, chocolat":660,
"Yogourt glacé, vanille":661,
"Gélatine, dessert, moins de calories, préparée (JelloMC)":662,
"Gélatine, dessert, préparée (JelloMC)":663,
"Mousse au chocolat, maison":664,
"À l'huile, régulier et micro-onde":665,
"Enrobé de caramel":666,
"Micro-onde, peu de gras et moins de sel":667,
"Nature":668,
"Bâtonnets soufflés au fromage (CheeziesMC)":669,
"Croustilles de maïs à saveur de nacho (DoritosMC)":670,
"Croustilles de maïs, nature":671,
"Pommes de terre déshydratées, nature (PringlesMC)":672,
"Pommes de terre, aromatisées":673,
"Pommes de terre, nature":674,
"Pommes de terre, nature, au four":675,
"Bâtonnet au boeuf (22cm long)":676,
"Bâtonnets aux graines de sésame, salés":677,
"Bretzels, durs, nature, non salés":678,
"Bretzels, durs, nature, salés":679,
"Croustilles de banane":680,
"Dragées à l'arachide (beer nut)":681,
"Galette de riz, nature":682,
"Noix et fruits séchés":683,
"Noix et fruits séchés, mélange tropical":684,
"Haricots de soya, rôtis, salés":685,
"Mélange d'amuse-gueules (MixMC)":686,
"Pâte de fruits déshydratés, tablette (Fruit To GoMC)":687,
"Café au lait (latté)":688,
"Café glacé, cappuccino - avec lait 2% (Tim HortonsMC)":689,
"Café glacé, cappuccino - original - avec crème (Tim HortonsMC)":690,
"Café glacé, Frappuccino (StarbucksMC)":691,
"Café infusé":692,
"Café infusé, décaféiné":693,
"Café instantané ordinaire, poudre et eau":694,
"Substitut de café, poudre et eau":695,
"Thé chai latte":696,
"Thé glacé, saveur de citron, poudre et eau":697,
"Thé glacé, saveur de citron, prêt-à-boire":698,
"Thé infusé":699,
"Tisane infusée":700,
"Cola":701,
"Cola, décaféiné":702,
"Cola, sucré à l'aspartame":703,
"Orangeade":704,
"Soda au citron et à la lime":705,
"Soda au gingembre":706,
"Soda nature":707,
"Soda tonique (quinine)":708,
"Soda, non cola, sucré à l'aspartame":709,
"Boisson à l'orange, avec vitamine C, prête-à-boire":710,
"Boisson à l'orange, poudre diluée, avec vitamine C (TangMc, QuenchMC, Rise'n ShineMC)":711,
"Boisson aux agrumes, congelée, diluée (Déli CinqMc)":712,
"Boisson, mélange de légumes et fruits (V8 SplashMc)":713,
"Boisson, punch aux fruits, avec vitamine C, poudre et eau":714,
"Boisson, punch aux fruits, poudre diluée (Kool-AidMc)":715,
"Boisson, punch aux fruits, prête-à-boire (Sunny DMC)":716,
"Boisson, saveur de fruits, peu de Calories, poudre et eau (Crystal LightMC)":717,
"Limonade, rose ou blanche, congelée, diluée":718,
"Boisson pour sportifs, à saveur de fruits, peu de Calories, prête-à-boire (GatoradeMc, PoweradeMc)":719,
"Boisson pour sportifs, à saveur de fruits, prête-à-boire (GatoradeMc, PoweradeMc)":720,
"Eau minérale (PerrierMc)":721,
"Eau municipale":722,
"Bière régulière (5% alcool par volume)":723,
"Bière sans alcool (Labbat .5MC)":724,
"Bière, élevée en alcool (7% alcool par volume)":725,
"Bière, légère (4% alcool par volume)":726,
"Cocktail, daiquiri":727,
"Cocktail, margarita":728,
"Cooler à la vodka":729,
"Liqueur, café et crème":730,
"Sangria":731,
"Spiritueux (gin, rhun, vodka, whisky)":732,
"Vin de dessert":733,
"Vin de table blanc":734,
"Vin de table rouge":735,
"Cornichons à l'aneth":736,
"Cornichons sucrés, tranches":737,
"Ketchup":738,
"Moutarde":739,
"Olives, marinées, en conserve ou bouteille":740,
"Olives, mûres, en conserve, jumbo":741,
"Relish sucrée":742,
"Salsa":743,
"Sauce à bifteck (HPMC, A1MC)":744,
"Sauce aigre-douce":745,
"Sauce barbecue":746,
"Sauce soya":747,
"Sauce teriyaki":748,
"Simili éclats de bacon":749,
"Trempette au fromage à la crème":750,
"Trempette à l'oignon":751,
"Trempette aux épinards":752,
"Sauce à la dinde, en conserve":753,
"Sauce au boeuf, déshydratée, préparée avec eau":754,
}