import re
import unicodedata

def normalize_string(s):
    # Replace non-ASCII characters with ASCII equivalents
    nfkd_form = unicodedata.normalize('NFKD', s)
    only_ascii = nfkd_form.encode('ASCII', 'ignore').decode('ASCII')

    # Remove parentheses and commas
    s_no_paren_comma = re.sub(r'[(),\']', '', only_ascii)

    # Replace spaces, hyphens, slashes, periods with underscores
    s_underscores = re.sub(r'[ /\-\.]', '_', s_no_paren_comma)

    # Replace % with p
    s_percent = s_underscores.replace('%', 'p')

    # Replace multiple consecutive underscores with a single one
    s_single_underscore = re.sub(r'_+', '_', s_percent)

    # Remove leading/trailing underscores
    s_trimmed = s_single_underscore.strip('_')

    # Ensure it starts with a letter or underscore (prepend underscore if starts with digit)
    if s_trimmed and s_trimmed[0].isdigit():
        s_trimmed = '_' + s_trimmed

    # Final check for any remaining invalid characters (though unlikely now)
    s_final = re.sub(r'[^a-zA-Z0-9_]', '', s_trimmed)

    # Handle edge case of empty string if all chars were removed
    if not s_final:
        return "_" # Or handle as an error/skip

    # Ensure it's not a Python keyword (unlikely for food names, but good practice)
    # import keyword
    # if keyword.iskeyword(s_final):
    #     s_final += '_'

    return s_final

aliments_list = ["Aliments",
"Cocktail de tomate et de palourdes",
"Jus de carottes",
"Jus de légumes, cocktail",
"Jus de légumes, cocktail, réduit en sodium",
"Jus de tomate",
"Jus de tomate, sans sel ajouté",
"Salade de chou, avec vinaigrette, maison",
"Salade de pommes de terre, maison",
"Sauce tomate pour spaghetti, en conserve",
"Sauce tomate, en conserve",
"Abricots crus",
"Abricots, séchés",
"Ananas, en conserve, dans du jus",
"Ananas, en dés",
"Avocat",
"Banane",
"Bleuets crus",
"Bleuets, congelés, non sucrés",
"Canneberges séchées, sucrées",
"Cerises de terre",
"Cerises sucrées",
"Clémentine",
"Cocktail aux fruits, en conserve, dans du jus",
"Cocktail aux fruits, en conserve, sirop léger",
"Dattes séchées",
"Figues crues",
"Figues séchées",
"Fraises",
"Fraises, congelées, non sucrées",
"Framboises",
"Grenade (9,5 cm diam)",
"Kiwi",
"Litchi",
"Mangue",
"Melon d'eau (pastèque), en dés",
"Melon, cantaloup, en dés",
"Melon, miel, en dés",
"Mûres",
"Nectarine",
"Orange",
"Pamplemousse blanc",
"Pamplemousse rose ou rouge",
"Papaye, en dés",
"Pêche",
"Pêches, en conserve, moitiés ou tranchées, dans du jus",
"Pêches, en conserve, moitiés ou tranchées, dans l'eau",
"Pêches, en conserve, moitiés ou tranchées, sirop léger",
"Plantain, cuit au four ou bouilli, tranché",
"Poire avec pelure",
"Poires, en conserve, moitiés, dans du jus",
"Poires, en conserve, moitiés, dans l'eau",
"Poires, en conserve, moitiés, sirop léger",
"Pomme avec pelure (7cm diam)",
"Prune",
"Pruneaux, séchés",
"Pruneaux, séchés, cuits sans sucre",
"Purée de pommes, non sucrée",
"Raisins",
"Raisins secs",
"Rhubarbe, congelée, cuite avec sucre",
"Salade de fruits tropicaux, en conserve, dans du jus",
"Salade de fruits tropicaux, en conserve, sirop épais",
"Tangerine (mandarine)",
"Tangerines (mandarines), en conserve, dans du jus, égouttées",
"Jus d'ananas, prêt-à-boire, avec vitamine C",
"Jus de canneberges, non sucré, prêt-à-boire",
"Jus de citron, en conserve ou en bouteille",
"Jus de grenade, prêt-à-boire",
"Jus de lime, en conserve ou en bouteille",
"Jus de pamplemousse, prêt-à-boire, non sucré ou fraîchement pressé",
"Jus de pamplemousse, prêt-à-boire, sucré",
"Jus de pomme, prêt-à-boire, avec vitamine C",
"Jus de pruneaux, prêt-à-boire",
"Jus de raisins, congelé, sucré, dilué, avec vitamine C",
"Jus de raisins, prêt-à-boire, avec vitamine C",
"Jus d'orange et pamplemousse, prêt-à-boire",
"Jus d'orange, congelé, dilué",
"Jus d'orange, fraises et banane, prêt-à-boire",
"Jus d'orange, prêt-à-boire",
"Jus d'orange, prêt-à-boire, réfrigéré, avec vitamine D et calcium",
"Jus, cocktail de canneberges et pomme, prêt-à-boire, peu de Calories, avec vitamine C",
"Jus, cocktail de canneberges, prêt-à-boire, avec vitamine C",
"Nectar, abricot",
"Nectar, mangue",
"Babeurre",
"Boisson de riz, nature et arômatisée, enrichie",
"Boisson de soya au chocolat, enrichie",
"Boisson de soya non sucrée, enrichie",
"Boisson de soya, originale et vanille, enrichie",
"Lait au chocolat, 1% M.G.",
"Lait au chocolat, 2% M.G.",
"Lait écrémé",
"Lait partiellement écrémé, 1% M.G.",
"Lait partiellement écrémé, 2% M.G.",
"Lait, partiellement écrémé, 2% M.G., avec solides de lait ajoutés",
"Lait entier, 3.3% M.G.",
"Lait concentré sucré, en conserve (Eagle BrandMC)",
"Lait évaporé, écrémé, en conserve, dilué, 0,2% M.G.",
"Lait évaporé, écrémé, en conserve, non dilué, 0,2% M.G.",
"Lait évaporé, entier, en conserve, dilué, 7,8% M.G.",
"Lait évaporé, entier, en conserve, non dilué, 7,8% M.G.",
"Lait évaporé, partiellement écrémé, en conserve, dilué, 2% M.G.",
"Lait évaporé, partiellement écrémé, en conserve, non dilué, 2% M.G.",
"Lait reconstitué à base de poudre de lait écrémé",
"Poudre de lait écrémé",
"Chocolat chaud, maison, cacao et lait 2%",
"Chocolat chaud, préparation commerciale et eau",
"Chocolat chaud, préparation commerciale et lait 2%",
"Chocolat chaud, préparation commerciale sucrée à l'aspartame et eau",
"Déjeuner instantané, préparation commerciale et lait 2%",
"Lait au chocolat, poudre arômatisée au chocolat et lait 2%",
"Lait au chocolat, sirop et lait 2%",
"Lait de poule",
"Lait frappé à la vanille",
"Lait frappé au chocolat",
"Fromage frais (Danimal MC, MinigoMC)",
"Kéfir, nature",
"Parfait au yogourt avec petits fruits et granola",
"Yogourt à boire",
"Yogourt, nature, 1-2% M.G.",
"Yogourt, nature, 2-4% M.G.",
"Yogourt, nature, sans gras",
"Yogourt, vanille ou fruits, 1-2% M.G.",
"Yogourt, vanille ou fruits, sans gras",
"Yogourt, vanille ou fruits, sans gras, sucré à l'édulcorant",
"Bleu",
"Brick",
"Brie",
"Camembert",
"Cheddar",
"Cheddar, peu de gras (18% M.G.)",
"Edam",
"Féta",
"Fromage à la crème, léger",
"Fromage à la crème, régulier",
"Fromage cottage (1% M.G.)",
"Fromage de chèvre à pâte molle",
"Fromage, imitation",
"Gouda",
"Gruyère",
"Mozzarella (22,5% M.G.)",
"Mozzarella partiellement écrémé (16,5% M.G.)",
"Parmesan, râpé",
"Préparation de fromage fondu à tartiner (Cheez WhizMC)",
"Préparation de fromage fondu à tartiner, léger (Cheez Whiz Légermc)",
"Préparation de fromage fondu, tranches minces",
"Préparation de fromage fondu, tranches minces, léger",
"Ricotta, partiellement écrémé",
"Romano, râpé",
"Suisse (Emmental)",
"Suisse fondu, tranches minces",
"Crème à fouetter, 35% M.G., non fouettée",
"Crème à fouetter, 35% M.G., sucrée, fouettée",
"Crème fouettée, en aérosol",
"Crème sure légère, 5% M.G.",
"Crème sure, 14% M.G.",
"De table, 18% M.G.",
"Moitié-moitié, 10% M.G.",
"Colorant à café, en poudre",
"Colorant à café, en poudre, léger",
"Colorant à café, liquide, congelé",
"Garniture à dessert congelée",
"Garniture à dessert congelée, peu de gras",
"Garniture à dessert en aérosol",
"Garniture à dessert en poudre, préparée avec lait 2%",
"Chocolat, prêt-à-manger",
"Chocolat, prêt-à-manger, sans gras",
"Riz, maison",
"Riz, prêt-à-manger",
"Tapioca, prêt-à-manger",
"Tapioca, prêt-à-manger, sans gras",
"Toutes saveurs, instantané, préparé avec lait 2%",
"Vanille, prêt-à-manger",
"Vanille, prêt-à-manger, sans gras",
"Blanc d'oeuf cuit",
"Jaune d'oeuf cuit",
"Oeuf cuit dur (à la coque)",
"Oeuf poché",
"Oeuf frit",
"Oeufs bénédictine",
"Oeufs brouillés, faits avec 2 oeufs",
"Omelette au fromage, faite avec 2 oeufs",
"Omelette espagnole (champignons, oignons, poivrons verts, tomates)",
"Omelette western (poivrons verts, jambon, oignons)",
"Succédané d'oeuf (jaunes remplacés), congelé, cuit",
"Aiglefin, au four ou grillé",
"Anchois, en conserve dans l'huile, égouttés",
"Bar (achigan), espèces diverses, au four ou grillé",
"Barbue de rivière à élevage, au four ou grillé",
"Cisco (hareng de lac), au four ou grillé",
"Cisco (hareng de lac), cru",
"Corégone de lac, autochtone, au four",
"Doré (jaune), au four ou grillé",
"Éperlan, pané et frit",
"Flétan de l'Atlantique ou Pacifique, au four ou grillé",
"Gefiltefish",
"Goberge de l'Atlantique, au four ou grillé",
"Grand brochet, au four ou grillé",
"Hareng de l'Atlantique, fumé et salé",
"Lotte (loche), crue",
"Maquereau bleu de l'Atlantique, au four ou grillé",
"Morue de l'Atlantique, au four ou grillé",
"Morue de l'Atlantique, déshydratée et salée, trempée dans l'eau",
"Omble chevalier, cuit",
"Ombre, au four ou grillé",
"Sardines de l'Atlantique, en conserve dans l'huile, égouttées avec arêtes",
"Sardines du Pacifique, en conserve dans de la sauce tomate, égouttées avec arêtes",
"Saumon coho d'élevage, au four ou grillé",
"Saumon de l'Atlantique d'élevage, au four ou grillé",
"Saumon fumé",
"Saumon fumé, lox",
"Saumon keta, au four ou grillé",
"Saumon keta, en conserve, égoutté, avec arêtes, sans sel",
"Saumon keta, en conserve, égoutté, avec arêtes, salé",
"Saumon rose, en conserve, égoutté, avec arêtes, salé",
"Saumon sockeye, au four ou grillé",
"Saumon, oeufs, crus",
"Saumon, royal ou quinnat, fumé, conserve",
"Sébaste de l'Atlantique, au four ou grillé",
"Sole (poisson plat), au four ou grillé",
"Thon, chair pâle, en conserve dans l'eau, égoutté, salé",
"Thon, chair pâle, en conserve dans l'huile, égoutté, salé",
"Truite arc-en-ciel d'élevage, au four ou grillée",
"Turbot, au four ou grillé",
"Vivaneau, espèces diverses, au four ou grillé",
"Crabe des neiges, bouilli ou cuit à la vapeur",
"Crabe, en conserve, égoutté",
"Crevettes, bouillies ou cuites à la vapeur",
"Écrevisse d'élevage, espèces diverses, bouillies ou cuites à la vapeur",
"Homard, bouilli ou cuit à la vapeur",
"Huîtres, bouillies ou cuites à la vapeur",
"Huîtres, crues",
"Huîtres, en conserve, chair et liquide",
"Moule, bouillies ou cuites à la vapeur",
"Palourdes, espèces diverses, bouillies ou cuites à la vapeur",
"Palourdes, espèces diverses, en conserve, égouttées",
"Pétoncles, cuits à la vapeur",
"Bâtonnets de poisson, congelés, réchauffés (10cm x 2,5cm x 1,3cm)",
"Beignet (galette) de crabe",
"Beignet (galette) de poisson",
"Calmars panés et frits",
"Caviar, noir ou rouge",
"Crevettes, panées et frites",
"Filet de poisson, dans une pâte à frire, frit",
"Salade de thon",
"Simili-crabe, à base de surimi",
"Aloyau, bœuf, maigre et gras, grillé",
"Boeuf à ragoût, maigre, mijoté",
"Boeuf haché, extra maigre, émietté, sauté",
"Boeuf haché, maigre, émietté, sauté",
"Boeuf haché, mi-maigre, émietté, sauté",
"Boeuf haché, régulier, émietté, sauté",
"Bout-de-côtes, maigre et gras, mijoté",
"Contre-filet, bifteck, maigre et gras, grillé",
"Côte, bifteck, maigre et gras, grillé",
"Côte, rôti, maigre et gras, rôti",
"Côtes croisées, rôti, maigre et gras, rôti",
"Coupes diverses, maigre et gras, cuites",
"Croupe, rôti, maigre et gras, rôti",
"Extérieur de ronde, bifteck, maigre et gras, braisé",
"Extérieur de ronde, rôti, maigre et gras, rôti",
"Faux filet, bifteck, maigre et gras, grillé",
"Flanc, bifteck, maigre et gras, braisé",
"Haut de surlonge, bifteck, maigre et gras, grillé",
"Intérieur de ronde, bifteck, maigre et gras, braisé",
"Intérieur de ronde, rôti, maigre et gras, rôti",
"Longe, filet, maigre et gras, rôti",
"Noix de ronde, bifteck, maigre et gras, braisé",
"Noix de ronde, rôti, maigre et gras, rôti",
"Palette, bifteck, maigre et gras, braisé",
"Palette, rôti, maigre et gras, braisé",
"Pointe de surlonge, rôti, maigre et gras, rôti",
"Cuisseau de veau, maigre et gras, pané, sauté",
"Cuisseau de veau, maigre et gras, rôti",
"Épaule, maigre et gras, rôtie",
"Escalope de veau de grain, sautée",
"Escalope de veau de lait, sautée",
"Longe, maigre et gras, rôtie",
"Veau à ragoût, maigre, braisé",
"Veau haché, grillé",
"Côtelette, longe, coupe du milieu, maigre et gras, grillée",
"Côtelette, longe, coupe du milieu, maigre et gras, sautée",
"Côtes levées de dos, maigre et gras, rôties",
"Côtes levées, maigre et gras, mijotées et rôties",
"Cuisse, croupe, maigre et gras, rôtie",
"Épaule, entière, maigre et gras, rôtie",
"Épaule, soc, maigre et gras, rôtie",
"Longe, bout de côtes, maigre et gras, grillée",
"Longe, bout de côtes, maigre et gras, sautée",
"Longe, filet, maigre, rôtie",
"Porc haché, maigre, sauté",
"Porc haché, mi-maigre, sauté",
"Américain, frais, côtes, maigre et gras, cuit",
"Américain, frais, épaule, entière, maigre et gras, cuit",
"Américain, frais, gigot, entier, maigre et gras, cuit",
"Américain, frais, haché, cuit",
"Américain, frais, jarret, maigre et gras, cuit",
"Américain, frais, longe, maigre et gras, cuit",
"Nouvelle-Zélande, congelé, côte, maigre et gras, rôti",
"Nouvelle-Zélande, congelé, coupes diverses, maigre et gras, cuit",
"Nouvelle-Zélande, congelé, épaule, entier, maigre et gras, braisé",
"Nouvelle-Zélande, congelé, gigot, entier, maigre et gras, rôti",
"Nouvelle-Zélande, congelé, jarret, maigre et gras, braisé",
"Nouvelle-Zélande, congelé, longe, maigre et gras, grillé",
"Bernache du Canada (outarde), viande, rôtie",
"Canard domestiqué, rôti",
"Canard sauvage, cuit",
"Dinde hachée, cuite",
"Dinde, viande blanche et peau, rôtie",
"Dinde, viande blanche, rôtie",
"Dinde, viande brune et peau, rôtie",
"Dinde, viande brune, rôtie",
"Lagopède, viande, cuite",
"Oie domestiquée, viande, rôtie",
"Poulet à griller, aile, viande et peau, rôtie",
"Poulet à griller, haut de cuisse, viande et peau, rôti",
"Poulet à griller, haut de cuisse, viande, rôti",
"Poulet à griller, pilon, viande et peau, rôti",
"Poulet à griller, pilon, viande, rôti",
"Poulet à griller, poitrine, viande et peau, rôtie",
"Poulet à griller, poitrine, viande, rôtie",
"Poulet à griller, viande et peau, rôties",
"Poulet à griller, viande, rôtie",
"Poulet de Cornouailles, viande et peau, rôties",
"Poulet haché, maigre, cuit",
"Tétras du Canada, viande, cuite",
"Autruche, intérieur de cuisse, cuite",
"Bison, rôti",
"Caribou (renne), rôti",
"Castor, rôti",
"Cheval, rôti",
"Chèvre, rôtie",
"Chevreuil, rôti",
"Émeu, intérieur de pilon, grillé",
"Lapin, coupes diverses, rôti",
"Narval, peau (muktuk), crue",
"Orignal, rôti",
"Ours, mijoté",
"Phoque, viande, bouillie",
"Coeur de boeuf, mijoté",
"Foie de boeuf, sauté",
"Foie de poulet, sauté",
"Foie de veau, sauté",
"Langue de boeuf, en conserve ou marinée",
"Ris de veau (thymus), braisé",
"Rognon de boeuf, mijoté",
"Bacon de dos, porc, grillé",
"Bacon, porc, grillé, sauté ou rôti",
"Bacon, porc, grillé, sauté ou rôti, réduit en sodium",
"Boeuf salé, pointe de poitrine, cuit",
"Bologne, boeuf et porc",
"Bologne, boeuf et porc, léger",
"Bologne, poulet",
"Cretons",
"Dinde en flocons, en conserve",
"Jambon en flocons, en conserve",
"Jambon, extra-maigre, en conserve",
"Jambon, maigre, en conserve",
"Jambon, maigre, rôti",
"Jambon, maigre et régulier, rôti",
"Pastrami au boeuf",
"Pâté de foie, en conserve",
"Pepperoni, porc et boeuf",
"Porc, salé, épaule, soc roulé (toupie), maigre et gras, rôti",
"Poulet en flocons, en conserve",
"Salami, boeuf et porc",
"Salami, boeuf et porc, sec",
"Salami, porc et boeuf, moins de sel",
"Saucisse à la dinde, cuite",
"Saucisse à déjeuner au porc et boeuf, cuite",
"Saucisse à déjeuner au porc, cuite",
"Saucisse Bratwurst au porc, cuite",
"Saucisse fumée au boeuf",
"Saucisse fumée au boeuf et porc",
"Saucisse fumée au boeuf et porc, légère",
"Saucisse fumée au poulet",
"Saucisse italienne au porc, cuite",
"Saucisse viennoise (cocktail), boeuf et porc, en conserve",
"Saucisson de foie de porc",
"Saucisson d'été au boeuf",
"Saucisson Kielbasa (Kolbassa), porc et boeuf",
"Viande froide, boeuf, tranché mince",
"Viande froide, jambon extra-maigre (5% gras)",
"Viande froide, jambon régulier (11% gras)",
"Viande froide, poitrine de dinde",
"Viande froide, poitrine de poulet",
"Viande froide, poitrine de poulet, peu de gras",
"Viande froide, simili poulet",
"Croquettes panées (genre poulet) sans viande",
"Galette de soya",
"Galette végétarienne",
"Sans-viande hachée",
"Saucisse fumée végétarienne",
"Tofu, régulier, ferme et extra ferme",
"Tofu, soyeux, mou",
"Viande froide végétarienne",
"Falafel, maison",
"Fèves au lard avec porc, en conserve",
"Fèves au lard nature ou végétariennes, en conserve",
"Fèves au lard, maison",
"Haricots à oeil noir, en conserve, non drainé",
"Haricots blancs, en conserve, non drainé",
"Haricots blancs, petits, en conserve, non drainé",
"Haricots de soya, bouillis",
"Haricots frits, en conserve",
"Haricots noirs, en conserve, non drainé",
"Haricots pinto, en conserve, non drainé",
"Haricots rouge foncé, en conserve, non drainé",
"Hoummos (hummus), commercial",
"Lentilles, bouillies, salées",
"Lentilles, roses, bouillies",
"Pois cassés, bouillis",
"Pois chiches (garbanzo), en conserve, non drainé",
"Arachides, toutes variétés, écalées, rôties",
"Arachides, toutes variétés, écalées, rôties à l'huile, salées",
"Beurre d'arachide crémeux, léger",
"Beurre d'arachide crémeux, matières grasses, sucre et sel ajoutés",
"Beurre d'arachide croquant, matières grasses, sucre et sel ajoutés",
"Beurre d'arachide naturel",
"Amandes séchées",
"Amandes, rôties dans l'huile",
"Amandes, rôties, salées",
"Grenoble, séchées",
"Macadamia, rôties, salées",
"Noisettes ou avelines, séchées",
"Noix d'acajou, rôties, salées",
"Noix de Brésil, séchées",
"Noix mélangées, rôties",
"Noix mélangées, rôties dans l'huile, salées",
"Noix mélangées, rôties, salées",
"Pacanes, séchées",
"Pignons, séchés",
"Pistaches, écalées, rôties, salées",
"Beurre d'acajou",
"Beurre d'amande",
"Beurre de sésame, tahini",
"Graines de citrouille et de courge, écalées, séchées",
"Graines de lin, entières et moulues",
"Graines de tournesol, rôties, salées, écalées",
"Pain à l'ail",
"Pommes de terre, frites",
"Rondelles d'oignon, panées et frites",
"Courgettes, panées et frites, bâtonnets",
"Donair / Gyro",
"Hamburger au fromage, galette double, avec condiments et légumes",
"Hamburger au fromage, une galette, nature",
"Hamburger végétarien, une galette, avec condiments et légumes",
"Hamburger, galette double, avec condiments",
"Hamburger, une galette, nature",
"Sandwich au poisson pané",
"Sandwich au poulet grillé, avec condiments et légumes",
"Sandwich au poulet pané, avec condiments et légumes",
"Sandwich déjeuner, bagel avec jambon, œuf et fromage",
"Sandwich déjeuner, biscuit poudre à pâte avec œuf, fromage et bacon",
"Sandwich déjeuner, muffin anglais avec œuf, fromage et bacon",
"Sandwich roulé au poulet ranch",
"Sandwich sous-marin (6 pouces), avec poulet grillé/rôti",
"Sandwich sous-marin (6 pouces), avec thon",
"Sandwich sous-marin (6 pouces), avec viandes froides",
"Sandwich sous-marin (6 pouces), végétarien",
"Boulettes de poulet à la sauce aigre-douce",
"Chow mein au poulet",
"Guy ding au poulet et aux amandes",
"Poulet Général Tao/Tso",
"Riz frit au poulet",
"Rouleau impérial (egg roll)",
"Sauté de boeuf et brocoli",
"Soupe aigre-piquante",
"Soupe won ton",
"Pizza avec fromage (moyenne - 12 pouces)",
"Pizza avec fromage et légumes (moyenne - 12 pouces)",
"Pizza avec fromage et pepperoni (moyenne - 12 pouces)",
"Pizza avec fromage, viande et légumes (moyenne - 12 pouces)",
"Chili con carne",
"Hot dog, nature",
"Poulet frit (morceaux)",
"Poulet, pané et frit, désossé (pépites)",
"Saucisse fumée enrobée de farine de maïs (PogoMC)",
"Burrito avec boeuf, fromage et piments forts",
"Burrito avec haricots et fromage",
"Fajita au poulet",
"Nachos avec fromage",
"Quesadilla avec viande",
"Salade de taco",
"Taco avec boeuf, fromage, salsa et légumes",
"Jambon",
"Oeufs durs",
"Rôti de bœuf, nature",
"Salade de saumon",
"Sandwich chaud au poulet",
"Sandwich club",
"César",
"César avec poulet",
"Grecque",
"Jardinière",
"Salade de pâtes avec légumes",
"Lasagne avec sauce à la viande (7,5cm x 9cm)",
"Lasagne, végétarienne (7,5cm x 9cm)",
"Macaroni à la viande avec soupe aux tomates",
"Macaroni au fromage (Dîner KraftMC)",
"Spaghetti avec sauce à la viande",
"Spaghetti avec sauce crémeuse",
"Boulettes de viande à la sauce aigre-douce",
"Pad Thaï",
"Pâté au boeuf, commercial, individuel",
"Pâté au poulet, commercial, individuel",
"Pâté chinois",
"Poulet au beurre",
"Poutine",
"Ragoût de bœuf",
"Samosa, végétarien",
"Sauté au boeuf",
"Sauté au poulet",
"Sauté au tofu",
"Sushi avec légumes, sans poisson",
"Sushi avec poisson",
"Tourtière maison (20cm diam)",
"Aux légumes, chunky",
"Boeuf ou poulet, bouillon/consommé",
"Boeuf, chunky",
"Chaudrée de palourdes, Manhattan",
"Minestrone, chunky",
"Pois cassés et jambon, chunky",
"Poulet et légumes, chunky",
"Poulet et nouilles, chunky",
"Poulet et nouilles, peu de gras, moins de sel",
"Boeuf et nouilles",
"Bouillon de poulet",
"Crème de champignons",
"Légumes et boeuf",
"Tomates",
"Tomates, moins de sel",
"Végétarienne aux légumes",
"Chaudrée de palourdes, Nouvelle-Angleterre",
"Crème de champignons, moins de sel",
"Crème de poulet",
"Crème de tomates",
"Minestrone",
"Nouilles Ramen, saveur de poulet, cuites",
"Oignon",
"Tomates et légumes",
"Crème de légumes",
"Légumes",
"Lentilles",
"Oignon, gratinée",
"Pois cassés avec jambon",
"Poulet et nouilles",
"Beurre",
"Margarine, dure, ImperialMc, huiles de soya et canola (hydrogénée)",
"Margarine, molle, Becel Mc, huiles de canola et carthame (non-hydrogenée)",
"Margarine, molle, Becel Mc, légère, huiles de canola et carthame (non-hydrogenée)",
"Margarine, molle, ChefmasterMc, huiles végétales non spécifiées (hydrogénée)",
"Margarine, molle, composite",
"Margarine, molle, ImperialMc, huile de soya (non-hydrogénée)",
"Margarine, molle, Lactantia Mc, huile de soya (hydrogénée)",
"Tartinade (20% beurre / 80% margarine)",
"Tartinade (50% beurre / 50% margarine)",
"Arachide",
"Canola",
"Graines de lin",
"Maïs",
"Olive",
"Pépins de raisins",
"Sésame",
"Soya",
"Tournesol",
"Gras de bacon",
"Saindoux",
"Shortening",
"César, crémeuse",
"César, crémeuse, peu de Calories",
"Française",
"Française, peu de gras",
"Fromage bleu",
"Fromage bleu, peu de Calories",
"Huile et vinaigre",
"Italienne",
"Italienne, peu de Calories",
"Mayonnaise",
"Mayonnaise, légère",
"Mille Îles",
"Mille Îles, peu de Calories",
"Ranch",
"Ranch, peu de gras",
"Sauce à salade, type mayonnaise",
"Sauce à salade, type mayonnaise, légère",
"Sauce à salade, type mayonnaise, sans gras",
"Vinaigrette crémeuse, sans gras",
"Vinaigrette non crémeuse, sans gras",
"À glacer (en poudre)",
"Blanc",
"Cassonade",
"Miel",
"Substitut de sucre, aspartame (EqualMc)",
"Substitut de sucre, sucralose (Splendamc)",
"Mélasse",
"Sirop de chocolat, consistance claire",
"Sirop de maïs",
"Sirop de table",
"Sirop d'érable",
"Confiture",
"Gelée",
"Marmalade",
"Tartinade de type confiture - double fruit",
"Tartinade de type confiture - double fruit - teneur réduite en sucre",
"Garniture au chocolat, consistance épaisse",
"Garniture aux fraises",
"Garniture ou tartinade, caramel écossais",
"Garniture pour tarte aux cerises, en conserve",
"Tartinade au chocolat et noisettes (NutellaMC)",
"Bonbon dur",
"Bonbon dur, moins de sucre",
"Bonbon enrobé de chocolat, sucré avec sorbitol",
"Bonbons haricots (jellybeans)",
"Caramel",
"Caramel au beurre",
"Caramel écossais",
"Croquants au sésame",
"Fudge, chocolat, maison",
"Gomme à mâcher",
"Gomme à mâcher sans sucre",
"Guimauves",
"Jujubes",
"Réglisse aux fraises (TwizzlersMC)",
"Roulé aux fruits",
"Skittles Mc",
"Sucre à la crème, maison",
"Amandes enrobées de chocolat",
"Arachides enrobées de chocolat",
"Biscuits enrobés de caramel recouvert de chocolat (TwixMc)",
"Caramel au beurre croquant, enrobé de chocolat (SkorMC)",
"Caramel avec noix, enrobé de chocolat (TurtlesMC)",
"Caramel enrobé de chocolat (RoloMC, CaramilkMC)",
"Chocolat au lait en tablette ou en brisures",
"Chocolat au lait et riz croquant (Nestlé CrunchMC)",
"Chocolat enrobé de bonbons (M&M'SMC, SmartiesMC)",
"Chocolat malt-nougat et caramel, enrobé de chocolat (MarsMC)",
"Chocolat, mi-sucré, en tablette ou en brisures",
"Fondant enrobé de chocolat (After EightMC)",
"Fudge, caramel et noix, enrobé de chocolat (Oh Henry!MC)",
"Gaufrette enrobée de chocolat (Kit KatMc, Coffee CrispMC)",
"Moules au beurre d'arachide (Reese's MC)",
"Noix de coco enrobée de chocolat (Bounty Mc, Almond JoyMC)",
"Raisins secs enrobés de chocolat (GlosetteMC)",
"Barre de fruits et jus",
"Barre de lait glacé au chocolat (FudgesicleMC)",
"Cornet de crème glacée, vanille, enrobé de chocolat, avec noix",
"Cornet de crème glacée, vanille, molle",
"Crème glacée molle avec biscuits OreoMc (Blizzard MC, McFlurryMc)",
"Crème glacée, chocolat",
"Crème glacée, fraises",
"Crème glacée, sandwich",
"Crème glacée, sans produits laitiers",
"Crème glacée, vanille, peu de gras",
"Crème glacée, vanille, peu de gras, sucrée à l'aspartame",
"Crème glacée, vanille, premium",
"Crème glacée, vanille, régulière",
"Sorbet à l'orange",
"Sucette glacée (popsicle)",
"Yogourt glacé, chocolat",
"Yogourt glacé, vanille",
"Gélatine, dessert, moins de calories, préparée (JelloMC)",
"Gélatine, dessert, préparée (JelloMC)",
"Mousse au chocolat, maison",
"À l'huile, régulier et micro-onde",
"Enrobé de caramel",
"Micro-onde, peu de gras et moins de sel",
"Nature",
"Bâtonnets soufflés au fromage (CheeziesMC)",
"Croustilles de maïs à saveur de nacho (DoritosMC)",
"Croustilles de maïs, nature",
"Pommes de terre déshydratées, nature (PringlesMC)",
"Pommes de terre, aromatisées",
"Pommes de terre, nature",
"Pommes de terre, nature, au four",
"Bâtonnet au boeuf (22cm long)",
"Bâtonnets aux graines de sésame, salés",
"Bretzels, durs, nature, non salés",
"Bretzels, durs, nature, salés",
"Croustilles de banane",
"Dragées à l'arachide (beer nut)",
"Galette de riz, nature",
"Noix et fruits séchés",
"Noix et fruits séchés, mélange tropical",
"Haricots de soya, rôtis, salés",
"Mélange d'amuse-gueules (MixMC)",
"Pâte de fruits déshydratés, tablette (Fruit To GoMC)",
"Café au lait (latté)",
"Café glacé, cappuccino - avec lait 2% (Tim HortonsMC)",
"Café glacé, cappuccino - original - avec crème (Tim HortonsMC)",
"Café glacé, Frappuccino (StarbucksMC)",
"Café infusé",
"Café infusé, décaféiné",
"Café instantané ordinaire, poudre et eau",
"Substitut de café, poudre et eau",
"Thé chai latte",
"Thé glacé, saveur de citron, poudre et eau",
"Thé glacé, saveur de citron, prêt-à-boire",
"Thé infusé",
"Tisane infusée",
"Cola",
"Cola, décaféiné",
"Cola, sucré à l'aspartame",
"Orangeade",
"Soda au citron et à la lime",
"Soda au gingembre",
"Soda nature",
"Soda tonique (quinine)",
"Soda, non cola, sucré à l'aspartame",
"Boisson à l'orange, avec vitamine C, prête-à-boire",
"Boisson à l'orange, poudre diluée, avec vitamine C (TangMc, QuenchMC, Rise'n ShineMC)",
"Boisson aux agrumes, congelée, diluée (Déli CinqMc)",
"Boisson, mélange de légumes et fruits (V8 SplashMc)",
"Boisson, punch aux fruits, avec vitamine C, poudre et eau",
"Boisson, punch aux fruits, poudre diluée (Kool-AidMc)",
"Boisson, punch aux fruits, prête-à-boire (Sunny DMC)",
"Boisson, saveur de fruits, peu de Calories, poudre et eau (Crystal LightMC)",
"Limonade, rose ou blanche, congelée, diluée",
"Boisson pour sportifs, à saveur de fruits, peu de Calories, prête-à-boire (GatoradeMc, PoweradeMc)",
"Boisson pour sportifs, à saveur de fruits, prête-à-boire (GatoradeMc, PoweradeMc)",
"Eau minérale (PerrierMc)",
"Eau municipale",
"Bière régulière (5% alcool par volume)",
"Bière sans alcool (Labbat .5MC)",
"Bière, élevée en alcool (7% alcool par volume)",
"Bière, légère (4% alcool par volume)",
"Cocktail, daiquiri",
"Cocktail, margarita",
"Cooler à la vodka",
"Liqueur, café et crème",
"Sangria",
"Spiritueux (gin, rhun, vodka, whisky)",
"Vin de dessert",
"Vin de table blanc",
"Vin de table rouge",
"Cornichons à l'aneth",
"Cornichons sucrés, tranches",
"Ketchup",
"Moutarde",
"Olives, marinées, en conserve ou bouteille",
"Olives, mûres, en conserve, jumbo",
"Relish sucrée",
"Salsa",
"Sauce à bifteck (HPMC, A1MC)",
"Sauce aigre-douce",
"Sauce barbecue",
"Sauce soya",
"Sauce teriyaki",
"Simili éclats de bacon",
"Trempette au fromage à la crème",
"Trempette à l'oignon",
"Trempette aux épinards",
"Sauce à la dinde, en conserve",
"Sauce au boeuf, déshydratée, préparée avec eau"


]

python_vars = aliments_list

# Print the results
count = 0
for var in python_vars:
    print(f'"{var}":{count},')
    count += 1
